name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.simplechatformatter.SimpleChatFormatter
version: ${version}
api-version: 1.13

softdepend:
  - PlaceholderAPI

commands:
  chatreload:
    description: Reloads the plugin
    aliases:
      - cr
      - scfreload
    permission: chat.reload

permissions:
  chat.reload:
    description: Allows the player to use /chatreload
  chat.format:
    description: Allows the player to use formatting codes
